import React from "react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import ThemeProvider from "@/components/theme-provider";
import NextAuthProvider from "@/components/auth-provider";
import Toast from "@/components/toast";

const poppins = Poppins({ 
  subsets: ["latin"], 
  weight: ["400", "500", "700", "900"], 
  style: ["italic", "normal"], 
  variable: "--font-poppins", 
});

export const metadata: Metadata = {
  title: "Hotel Management App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Toast />
        <main className="font-normal">
          <NextAuthProvider>
            <ThemeProvider>
              <Header />
              {children}
              <Footer />
            </ThemeProvider>
          </NextAuthProvider>
        </main>
      </body>
    </html>
  );
}
